[workspace]
resolver = "2"
members = ["bin/*"]

[workspace.dependencies]
anyhow = "1.0"
futures = "0.3"
tokio = { version = "1", features = ["full"] }

sui-sdk = { git = "https://github.com/MystenLabs/sui", package = "sui-sdk" }
